- hosts: localhost  
  vars:
    i3_tags: ["install", "core", "i3"]
    picom_dir: "{{ lookup('env', 'HOME') }}/picom"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/productivity-tools-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/i3-setup.yml
    - include: tasks/brightness-control-setup.yml
    - include: tasks/bluetooth-setup.yml
    - include: tasks/dotfiles.yml
