#- name: Install System Packages 4 (i3, dconf-editor, pavucontrol, ubuntu-mate-desktop)
#  become: true
#  apt:
#    name: [ "i3", "dconf-editor", "pavucontrol"]
#  tags: "{{ i3_tags }}"
#
#- name: dconf i3
#  shell: dconf-editor write /org/mate/desktop/session/required-components/windowmanager "'i3'"
#  tags: "{{ i3_tags }}"
#
#- name: dconf i3
#  shell: dconf-editor write /org/mate/desktop/background/show-desktop-icons "false"
#  tags: "{{ i3_tags }}"
#
- name: i3 dependencies
  become: true
  apt:
    name: [ "libxext-dev", "libxcb1-dev", "libxcb-damage0-dev", "libxcb-dpms0-dev", 
      "libxcb-xfixes0-dev", "libxcb-shape0-dev", "libxcb-render-util0-dev", 
      "libxcb-render0-dev", "libxcb-randr0-dev", "libxcb-composite0-dev", 
      "libxcb-image0-dev", "libxcb-present-dev", "libxcb-glx0-dev", "libpixman-1-dev", 
      "libdbus-1-dev", "libconfig-dev", "libgl-dev", "libegl-dev", "libpcre2-dev", 
      "libevdev-dev", "uthash-dev", "libev-dev", "libx11-xcb-dev", "meson", "feh",
      "libxcb-xinerama0" ]
  tags: "{{ i3_tags }}"

- name: Clone picom
  ansible.builtin.git:
    repo: 'https://github.com/yshui/picom.git'
    dest: "{{ picom_dir }}"
    recursive: yes
    update: yes
    version: v10.2
  tags: "{{ i3_tags }}"

- name: Build and install picom
  become: true
  shell: meson --buildtype=release . build && ninja -C build install
  args:
    chdir: "{{ picom_dir }}"
  ignore_errors: yes
  tags: "{{ i3_tags }}"

- name: install polybar 
  become: true
  apt:
    name: [ "polybar" ]
  tags: "{{ i3_tags }}"

- name: install i3-resurrect
  pip:
    name:
      - i3-resurrect 
  tags: "{{ i3_tags }}"

- name: install playerctl
  become: true
  shell: wget http://ftp.nl.debian.org/debian/pool/main/p/playerctl/libplayerctl2_2.0.1-1_amd64.deb && wget http://ftp.nl.debian.org/debian/pool/main/p/playerctl/playerctl_2.0.1-1_amd64.deb && sudo dpkg -i libplayerctl2_2.0.1-1_amd64.deb playerctl_2.0.1-1_amd64.deb 
  args:
    chdir: "{{ lookup('env', 'HOME') }}"
  tags: "{{ i3_tags }}"

- name: install bluetooth dependencies 
  become: true 
  shell: sudo apt install bluez bluez-tools -y  && sudo apt install blueman -y 
  tags:
    - install
