- name: Install packages
  become: true
  apt:
    name: [ "tmux", "wireshark", "fzf", "gimp", "xclip", "tldr", "ripgrep", "shutter", "tree", "zathura", "texlive" ]
  tags:
    - install
    - productivity

- name: Download pandoc deb
  ansible.builtin.get_url:
    url: https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb
    dest: "{{ lookup('env', 'HOME') }}"
  tags:
    - install
    - productivity

- name: Install pandoc
  become: true
  shell: dpkg -i {{ lookup('env', 'HOME') }}/pandoc-2.19.2-1-amd64.deb
  tags:
    - install
    - productivity
